INSERT INTO Account (UserName, Password) VALUES ( 'Mark','Whatastory')
INSERT INTO Account (UserName, Password) VALUES ( 'Tommy','WhyLisa')
INSERT INTO Account (UserName, Password) VALUES ( 'Denny','wheresmyfmoney')

INSERT INTO GODS (God, GodType, Pantheon) VALUES ('Agni', 'Mage', 'Hindu')
INSERT INTO GODS (God, GodType, Pantheon) VALUES ('Fenrir', 'Assassin', 'Norse')
INSERT INTO GODS (God, GodType, Pantheon) VALUES ('Susano', 'Assassin', 'Japanese')
INSERT INTO GODS (God, GodType, Pantheon) VALUES ('Kukulkan', 'Mage', 'Mayan')
INSERT INTO GODS (God, GodType, Pantheon) VALUES ('Xbalanque', 'Hunter', 'Mayan')
INSERT INTO GODS (God, GodType, Pantheon) VALUES ('Athena', 'Guardian', 'Greek')
INSERT INTO GODS (God, GodType, Pantheon) VALUES ('Cu Chulain', 'Warrior', 'Celtic')